use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum ToolCategory {
    Reconnaissance, WebApplication, Exploitation, PasswordAttacks,
    Network, Wireless, Forensics, PostExploitation,
    SocialEngineering, VulnerabilityAnalysis, Evasion, CryptoSteganography,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Difficulty { Beginner, Intermediate, Advanced, Expert }

// Use a plain struct for the static catalog (no Deserialize needed for statics)
pub struct Tool {
    pub name:             &'static str,
    pub display_name:     &'static str,
    pub description:      &'static str,
    pub long_description: &'static str,
    pub icon:             &'static str,
    pub category:         ToolCategory,
    pub subcategory:      &'static str,
    pub command:          &'static str,
    pub package:          &'static str,
    pub tags:             &'static [&'static str],
    pub difficulty:       Difficulty,
    pub color:            &'static str,
    pub website:          &'static str,
    pub is_gui:           bool,
}

// Serializable version for IPC / JSON export
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ToolRecord {
    pub name:             String,
    pub display_name:     String,
    pub description:      String,
    pub long_description: String,
    pub icon:             String,
    pub category:         ToolCategory,
    pub subcategory:      String,
    pub command:          String,
    pub package:          String,
    pub tags:             Vec<String>,
    pub difficulty:       Difficulty,
    pub color:            String,
    pub website:          String,
    pub is_gui:           bool,
}

impl From<&'static Tool> for ToolRecord {
    fn from(t: &'static Tool) -> Self {
        Self {
            name:             t.name.into(),
            display_name:     t.display_name.into(),
            description:      t.description.into(),
            long_description: t.long_description.into(),
            icon:             t.icon.into(),
            category:         t.category.clone(),
            subcategory:      t.subcategory.into(),
            command:          t.command.into(),
            package:          t.package.into(),
            tags:             t.tags.iter().map(|s| s.to_string()).collect(),
            difficulty:       t.difficulty.clone(),
            color:            t.color.into(),
            website:          t.website.into(),
            is_gui:           t.is_gui,
        }
    }
}

pub const RED_TEAM_TOOLS: &[Tool] = &[
    // ── RECONNAISSANCE ─────────────────────────────────────────────────────
    Tool {
        name: "nmap", display_name: "Nmap",
        description: "Network discovery & port scanner",
        long_description: "Industry-standard network scanner. SYN/TCP/UDP/ICMP, OS detection, 600+ NSE scripts.",
        icon: "🔍", category: ToolCategory::Reconnaissance, subcategory: "Network Scanning",
        command: "nmap", package: "nmap",
        tags: &["network","ports","discovery","nse","scan"],
        difficulty: Difficulty::Beginner, color: "#ef4444",
        website: "https://nmap.org", is_gui: false,
    },
    Tool {
        name: "masscan", display_name: "Masscan",
        description: "Mass port scanner — 10M packets/sec",
        long_description: "Fastest internet port scanner. Raw SYN packets asynchronously.",
        icon: "⚡", category: ToolCategory::Reconnaissance, subcategory: "Network Scanning",
        command: "masscan", package: "masscan",
        tags: &["network","ports","fast","raw","syn"],
        difficulty: Difficulty::Intermediate, color: "#f97316",
        website: "https://github.com/robertdavidgraham/masscan", is_gui: false,
    },
    Tool {
        name: "rustscan", display_name: "RustScan",
        description: "Rust port scanner — all 65535 ports in 3 seconds",
        long_description: "Scans all 65535 ports in under 3 seconds, pipes to Nmap.",
        icon: "🦀", category: ToolCategory::Reconnaissance, subcategory: "Network Scanning",
        command: "rustscan", package: "rustscan",
        tags: &["rust","fast","ports","nmap"],
        difficulty: Difficulty::Beginner, color: "#f97316",
        website: "https://github.com/RustScan/RustScan", is_gui: false,
    },
    Tool {
        name: "amass", display_name: "Amass",
        description: "In-depth attack surface mapping",
        long_description: "OWASP attack surface mapping. DNS, CT logs, APIs, brute-force.",
        icon: "🗺", category: ToolCategory::Reconnaissance, subcategory: "OSINT",
        command: "amass", package: "amass",
        tags: &["osint","dns","subdomains","attack-surface","ct"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://github.com/owasp-amass/amass", is_gui: false,
    },
    Tool {
        name: "subfinder", display_name: "Subfinder",
        description: "Passive subdomain discovery — 40+ sources",
        long_description: "Fast passive subdomain enumeration using 40+ sources.",
        icon: "🔎", category: ToolCategory::Reconnaissance, subcategory: "OSINT",
        command: "subfinder", package: "subfinder",
        tags: &["osint","dns","subdomains","passive","recon"],
        difficulty: Difficulty::Beginner, color: "#eab308",
        website: "https://github.com/projectdiscovery/subfinder", is_gui: false,
    },
    Tool {
        name: "theHarvester", display_name: "theHarvester",
        description: "OSINT: emails, subdomains, IPs, employees",
        long_description: "Gathers emails, names, subdomains from 40+ public sources.",
        icon: "🌾", category: ToolCategory::Reconnaissance, subcategory: "OSINT",
        command: "theHarvester", package: "theharvester",
        tags: &["osint","email","linkedin","employees","google"],
        difficulty: Difficulty::Beginner, color: "#eab308",
        website: "https://github.com/laramies/theHarvester", is_gui: false,
    },
    Tool {
        name: "shodan", display_name: "Shodan CLI",
        description: "Internet device search engine",
        long_description: "CLI to Shodan — find exposed services, cameras, ICS/SCADA.",
        icon: "👁", category: ToolCategory::Reconnaissance, subcategory: "OSINT",
        command: "shodan", package: "python-shodan",
        tags: &["osint","iot","ics","internet","exposure","api"],
        difficulty: Difficulty::Intermediate, color: "#f97316",
        website: "https://shodan.io", is_gui: false,
    },
    Tool {
        name: "enum4linux-ng", display_name: "enum4linux-ng",
        description: "Windows/Samba SMB enumeration",
        long_description: "Next-gen enum4linux. Users, groups, shares via SMB/MSRPC.",
        icon: "🪟", category: ToolCategory::Reconnaissance, subcategory: "Windows/AD",
        command: "enum4linux-ng", package: "enum4linux-ng",
        tags: &["smb","windows","ad","shares","users","rpc"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://github.com/cddmp/enum4linux-ng", is_gui: false,
    },
    Tool {
        name: "kerbrute", display_name: "Kerbrute",
        description: "Kerberos user enumeration & password spray",
        long_description: "Enumerate valid AD accounts via Kerberos Pre-Authentication.",
        icon: "🎫", category: ToolCategory::Reconnaissance, subcategory: "Windows/AD",
        command: "kerbrute", package: "kerbrute",
        tags: &["kerberos","ad","windows","spray","users"],
        difficulty: Difficulty::Intermediate, color: "#eab308",
        website: "https://github.com/ropnop/kerbrute", is_gui: false,
    },
    Tool {
        name: "dnsrecon", display_name: "DNSRecon",
        description: "DNS enumeration & zone transfer",
        long_description: "Standard, reverse, MX, SOA, SPF records. Zone transfers, brute-force.",
        icon: "📡", category: ToolCategory::Reconnaissance, subcategory: "DNS",
        command: "dnsrecon", package: "dnsrecon",
        tags: &["dns","zone-transfer","records","brute","ptr"],
        difficulty: Difficulty::Beginner, color: "#ef4444",
        website: "https://github.com/darkoperator/dnsrecon", is_gui: false,
    },
    Tool {
        name: "smbmap", display_name: "SMBMap",
        description: "SMB share enumeration & access checker",
        long_description: "Enumerate SMB shares, check permissions, search sensitive files.",
        icon: "📂", category: ToolCategory::Reconnaissance, subcategory: "Windows/AD",
        command: "smbmap", package: "smbmap",
        tags: &["smb","shares","permissions","files","windows"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://github.com/ShawnDEvans/smbmap", is_gui: false,
    },
    // ── WEB APPLICATION ────────────────────────────────────────────────────
    Tool {
        name: "burpsuite", display_name: "Burp Suite",
        description: "The definitive web security testing platform",
        long_description: "Interceptor, repeater, intruder, scanner, collaborator.",
        icon: "🕷", category: ToolCategory::WebApplication, subcategory: "Web Proxy",
        command: "burpsuite", package: "burpsuite",
        tags: &["proxy","web","scanner","intercept","fuzzing","oob"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://portswigger.net/burp", is_gui: true,
    },
    Tool {
        name: "sqlmap", display_name: "SQLMap",
        description: "Automated SQL injection & DB takeover",
        long_description: "Auto-detects and exploits SQL injection. 6 techniques, 40+ DBs.",
        icon: "🗄", category: ToolCategory::WebApplication, subcategory: "Injection",
        command: "sqlmap", package: "sqlmap",
        tags: &["sql","injection","database","automation","dump"],
        difficulty: Difficulty::Beginner, color: "#ef4444",
        website: "https://sqlmap.org", is_gui: false,
    },
    Tool {
        name: "nuclei", display_name: "Nuclei",
        description: "Template-based vulnerability scanner",
        long_description: "Community-driven scanner with 7000+ YAML templates.",
        icon: "☢", category: ToolCategory::WebApplication, subcategory: "Scanning",
        command: "nuclei", package: "nuclei",
        tags: &["cve","templates","yaml","cloud","automation","fast"],
        difficulty: Difficulty::Beginner, color: "#eab308",
        website: "https://projectdiscovery.io/nuclei", is_gui: false,
    },
    Tool {
        name: "ffuf", display_name: "ffuf",
        description: "Fast web fuzzer — dirs, params, vhosts",
        long_description: "Go-based web fuzzer. Directory, parameter, vhost fuzzing.",
        icon: "⚡", category: ToolCategory::WebApplication, subcategory: "Fuzzing",
        command: "ffuf", package: "ffuf",
        tags: &["fuzzing","directories","params","vhosts","go","wordlist"],
        difficulty: Difficulty::Beginner, color: "#f97316",
        website: "https://github.com/ffuf/ffuf", is_gui: false,
    },
    Tool {
        name: "feroxbuster", display_name: "Feroxbuster",
        description: "Fast recursive content discovery",
        long_description: "Rust-based content discovery. Recursive scanning, wildcard detection.",
        icon: "🐾", category: ToolCategory::WebApplication, subcategory: "Discovery",
        command: "feroxbuster", package: "feroxbuster",
        tags: &["directories","recursive","rust","discovery","web"],
        difficulty: Difficulty::Beginner, color: "#f97316",
        website: "https://github.com/epi052/feroxbuster", is_gui: false,
    },
    Tool {
        name: "dalfox", display_name: "DalFox",
        description: "XSS scanner with parameter analysis",
        long_description: "Fast XSS scanner. Blind XSS, DOM XSS, reflected XSS.",
        icon: "🦊", category: ToolCategory::WebApplication, subcategory: "XSS",
        command: "dalfox", package: "dalfox",
        tags: &["xss","parameters","dom","blind","scanning"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://github.com/hahwul/dalfox", is_gui: false,
    },
    Tool {
        name: "nikto", display_name: "Nikto",
        description: "Web server vulnerability scanner",
        long_description: "6700+ tests against web servers. Misconfigurations, outdated software.",
        icon: "🌐", category: ToolCategory::WebApplication, subcategory: "Scanning",
        command: "nikto", package: "nikto",
        tags: &["web","server","misconfig","files","outdated","scan"],
        difficulty: Difficulty::Beginner, color: "#f97316",
        website: "https://cirt.net/nikto2", is_gui: false,
    },
    Tool {
        name: "wpscan", display_name: "WPScan",
        description: "WordPress security scanner",
        long_description: "Enumerate users, plugins, themes, vulnerability database lookup.",
        icon: "📰", category: ToolCategory::WebApplication, subcategory: "CMS",
        command: "wpscan", package: "wpscan",
        tags: &["wordpress","cms","plugins","themes","users","enum"],
        difficulty: Difficulty::Beginner, color: "#ef4444",
        website: "https://wpscan.com", is_gui: false,
    },
    // ── EXPLOITATION ───────────────────────────────────────────────────────
    Tool {
        name: "msfconsole", display_name: "Metasploit Framework",
        description: "The world's most used penetration testing framework",
        long_description: "Hundreds of exploits, payloads, post-exploitation modules.",
        icon: "💉", category: ToolCategory::Exploitation, subcategory: "Framework",
        command: "msfconsole", package: "metasploit",
        tags: &["exploits","payloads","post","msf","meterpreter"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://metasploit.com", is_gui: false,
    },
    Tool {
        name: "impacket-scripts", display_name: "Impacket",
        description: "Network protocol attack toolkit",
        long_description: "secretsdump, psexec, wmiexec, ntlmrelayx, ticketer, 30+ tools.",
        icon: "📦", category: ToolCategory::Exploitation, subcategory: "Windows/AD",
        command: "impacket-secretsdump", package: "impacket",
        tags: &["smb","windows","ad","relay","kerberos","ntlm"],
        difficulty: Difficulty::Advanced, color: "#ef4444",
        website: "https://github.com/fortra/impacket", is_gui: false,
    },
    Tool {
        name: "evil-winrm", display_name: "Evil-WinRM",
        description: "WinRM shell for Windows pentesting",
        long_description: "WinRM shell with file upload/download, pass-the-hash, HTTPS.",
        icon: "👿", category: ToolCategory::Exploitation, subcategory: "Windows/AD",
        command: "evil-winrm", package: "evil-winrm",
        tags: &["winrm","windows","shell","powershell","pth"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://github.com/Hackplayers/evil-winrm", is_gui: false,
    },
    Tool {
        name: "certipy-ad", display_name: "Certipy",
        description: "Active Directory Certificate Services abuse",
        long_description: "Enumerate and abuse ADCS (ESC1-ESC8). PKINIT auth.",
        icon: "📜", category: ToolCategory::Exploitation, subcategory: "Windows/AD",
        command: "certipy", package: "certipy-ad",
        tags: &["adcs","certificates","ad","windows","esc","pki"],
        difficulty: Difficulty::Advanced, color: "#eab308",
        website: "https://github.com/ly4k/Certipy", is_gui: false,
    },
    Tool {
        name: "crackmapexec", display_name: "CrackMapExec",
        description: "Swiss army knife for Windows/AD attacks",
        long_description: "SMB, WinRM, LDAP, RDP, MSSQL attacker. PtH, PtT, spray.",
        icon: "🗺", category: ToolCategory::Exploitation, subcategory: "Windows/AD",
        command: "crackmapexec", package: "crackmapexec",
        tags: &["smb","winrm","ldap","spray","pth","ad"],
        difficulty: Difficulty::Intermediate, color: "#f97316",
        website: "https://github.com/Porchetta-Industries/CrackMapExec", is_gui: false,
    },
    Tool {
        name: "responder", display_name: "Responder",
        description: "LLMNR/NBT-NS/MDNS poisoner",
        long_description: "Poisons LLMNR, NBT-NS, MDNS to capture NTLMv1/v2 hashes.",
        icon: "☠", category: ToolCategory::Exploitation, subcategory: "Windows/AD",
        command: "responder", package: "responder",
        tags: &["llmnr","nbt-ns","ntlm","poison","mitm","hashes"],
        difficulty: Difficulty::Intermediate, color: "#f97316",
        website: "https://github.com/lgandx/Responder", is_gui: false,
    },
    Tool {
        name: "searchsploit", display_name: "SearchSploit",
        description: "Offline ExploitDB search",
        long_description: "Search the Exploit Database locally. Update with searchsploit -u.",
        icon: "📚", category: ToolCategory::Exploitation, subcategory: "Framework",
        command: "searchsploit", package: "exploitdb",
        tags: &["exploitdb","search","offline","cve","shellcode"],
        difficulty: Difficulty::Beginner, color: "#ef4444",
        website: "https://exploit-db.com", is_gui: false,
    },
    // ── PASSWORD ATTACKS ───────────────────────────────────────────────────
    Tool {
        name: "hashcat", display_name: "Hashcat",
        description: "World's fastest GPU-accelerated password recovery",
        long_description: "350+ hash types. GPU/CPU with OpenCL. All attack modes.",
        icon: "🔓", category: ToolCategory::PasswordAttacks, subcategory: "Hash Cracking",
        command: "hashcat", package: "hashcat",
        tags: &["gpu","hash","cracking","wordlist","rules","opencl","ntlm","wpa"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://hashcat.net", is_gui: false,
    },
    Tool {
        name: "john", display_name: "John the Ripper",
        description: "Classic multi-platform password cracker",
        long_description: "Auto-detects hash types. 50+ cracking modules.",
        icon: "🔐", category: ToolCategory::PasswordAttacks, subcategory: "Hash Cracking",
        command: "john", package: "john",
        tags: &["hash","cracking","cpu","wordlist","shadow","formats"],
        difficulty: Difficulty::Beginner, color: "#f97316",
        website: "https://www.openwall.com/john", is_gui: false,
    },
    Tool {
        name: "hydra", display_name: "THC Hydra",
        description: "Parallelized network login brute-forcer",
        long_description: "50+ protocols: FTP, HTTP, SMB, RDP, SSH, VNC, MySQL.",
        icon: "🔑", category: ToolCategory::PasswordAttacks, subcategory: "Network Brute-Force",
        command: "hydra", package: "hydra",
        tags: &["brute-force","network","ssh","ftp","http","rdp","login"],
        difficulty: Difficulty::Beginner, color: "#eab308",
        website: "https://github.com/vanhauser-thc/thc-hydra", is_gui: false,
    },
    Tool {
        name: "pypykatz", display_name: "Pypykatz",
        description: "Mimikatz in pure Python",
        long_description: "Parse LSASS dumps, DPAPI blobs, SAM databases on Linux.",
        icon: "🐍", category: ToolCategory::PasswordAttacks, subcategory: "Credential Dumping",
        command: "pypykatz", package: "python-pypykatz",
        tags: &["mimikatz","lsass","credentials","python","dpapi","sam"],
        difficulty: Difficulty::Advanced, color: "#ef4444",
        website: "https://github.com/skelsec/pypykatz", is_gui: false,
    },
    Tool {
        name: "cewl", display_name: "CeWL",
        description: "Custom wordlist generator from target website",
        long_description: "Spiders a URL, generates wordlists from site content.",
        icon: "📝", category: ToolCategory::PasswordAttacks, subcategory: "Wordlist Generation",
        command: "cewl", package: "cewl",
        tags: &["wordlist","spider","website","custom","targeted"],
        difficulty: Difficulty::Beginner, color: "#f97316",
        website: "https://github.com/digininja/CeWL", is_gui: false,
    },
    // ── NETWORK ────────────────────────────────────────────────────────────
    Tool {
        name: "wireshark", display_name: "Wireshark",
        description: "Network protocol analyzer",
        long_description: "3000+ protocols, real-time capture, SSL/TLS decryption.",
        icon: "📶", category: ToolCategory::Network, subcategory: "Packet Analysis",
        command: "wireshark", package: "wireshark-qt",
        tags: &["packets","protocols","capture","analysis","ssl","voip"],
        difficulty: Difficulty::Intermediate, color: "#3b82f6",
        website: "https://wireshark.org", is_gui: true,
    },
    Tool {
        name: "bettercap", display_name: "Bettercap",
        description: "MitM attacks & network recon",
        long_description: "ARP/DNS spoofing, HTTP/S proxy, WiFi attacks, BLE, HID.",
        icon: "🎯", category: ToolCategory::Network, subcategory: "MitM",
        command: "bettercap", package: "bettercap",
        tags: &["mitm","arp","dns","proxy","wifi","ble","hid"],
        difficulty: Difficulty::Advanced, color: "#ef4444",
        website: "https://bettercap.org", is_gui: false,
    },
    Tool {
        name: "tcpdump", display_name: "tcpdump",
        description: "CLI packet capture & analysis",
        long_description: "Command-line packet analyzer using libpcap. Fast, BPF filters.",
        icon: "📡", category: ToolCategory::Network, subcategory: "Packet Capture",
        command: "tcpdump", package: "tcpdump",
        tags: &["packets","capture","bpf","cli","filter","pcap"],
        difficulty: Difficulty::Intermediate, color: "#22c55e",
        website: "https://tcpdump.org", is_gui: false,
    },
    Tool {
        name: "nc", display_name: "Netcat",
        description: "TCP/UDP swiss army knife",
        long_description: "TCP/UDP connections, file transfer, bind/reverse shells.",
        icon: "🔌", category: ToolCategory::Network, subcategory: "Utilities",
        command: "nc", package: "gnu-netcat",
        tags: &["tcp","udp","shell","transfer","listen","pivot"],
        difficulty: Difficulty::Beginner, color: "#22c55e",
        website: "https://netcat.sourceforge.net", is_gui: false,
    },
    Tool {
        name: "proxychains", display_name: "ProxyChains",
        description: "Chain proxies for TCP app anonymization",
        long_description: "SOCKS4/5 or HTTP proxies. Chain, dynamic, random. Use with Tor.",
        icon: "⛓", category: ToolCategory::Network, subcategory: "Anonymization",
        command: "proxychains", package: "proxychains-ng",
        tags: &["proxy","socks","anonymity","chain","tor","pivot"],
        difficulty: Difficulty::Beginner, color: "#eab308",
        website: "https://github.com/haad/proxychains", is_gui: false,
    },
    // ── WIRELESS ──────────────────────────────────────────────────────────
    Tool {
        name: "aircrack-ng", display_name: "Aircrack-ng",
        description: "Complete WiFi security auditing suite",
        long_description: "Monitor, inject, crack WEP/WPA, fake AP.",
        icon: "📡", category: ToolCategory::Wireless, subcategory: "WiFi Auditing",
        command: "aircrack-ng", package: "aircrack-ng",
        tags: &["wifi","wpa","wep","monitor","inject","handshake"],
        difficulty: Difficulty::Intermediate, color: "#eab308",
        website: "https://aircrack-ng.org", is_gui: false,
    },
    Tool {
        name: "wifite", display_name: "Wifite2",
        description: "Automated WiFi auditor",
        long_description: "Automates WPS (Pixie), WPA (PMKID, handshake), WEP attacks.",
        icon: "🤖", category: ToolCategory::Wireless, subcategory: "WiFi Auditing",
        command: "wifite", package: "wifite",
        tags: &["wifi","wpa","wps","automated","pmkid","wep"],
        difficulty: Difficulty::Beginner, color: "#eab308",
        website: "https://github.com/derv82/wifite2", is_gui: false,
    },
    Tool {
        name: "hcxdumptool", display_name: "hcxdumptool",
        description: "PMKID capture — clientless WPA cracking",
        long_description: "Captures PMKID directly from AP. Works with Hashcat.",
        icon: "📸", category: ToolCategory::Wireless, subcategory: "WiFi Capture",
        command: "hcxdumptool", package: "hcxtools",
        tags: &["pmkid","capture","eapol","hashcat","clientless","wpa"],
        difficulty: Difficulty::Advanced, color: "#f97316",
        website: "https://github.com/ZerBea/hcxdumptool", is_gui: false,
    },
    // ── FORENSICS ─────────────────────────────────────────────────────────
    Tool {
        name: "ghidra", display_name: "Ghidra",
        description: "NSA reverse engineering suite",
        long_description: "NSA's open source RE framework. Full decompiler, scripting API.",
        icon: "🐉", category: ToolCategory::Forensics, subcategory: "Reverse Engineering",
        command: "ghidra", package: "ghidra",
        tags: &["re","disassembly","decompiler","nsa","binary","arm","x64"],
        difficulty: Difficulty::Expert, color: "#ef4444",
        website: "https://ghidra-sre.org", is_gui: true,
    },
    Tool {
        name: "r2", display_name: "Radare2",
        description: "Unix-like reverse engineering framework",
        long_description: "Disassembly, debugging, binary analysis, exploitation.",
        icon: "🔭", category: ToolCategory::Forensics, subcategory: "Reverse Engineering",
        command: "r2", package: "radare2",
        tags: &["re","debugging","binary","analysis","patching","scripting"],
        difficulty: Difficulty::Expert, color: "#f97316",
        website: "https://radare.org", is_gui: false,
    },
    Tool {
        name: "volatility3", display_name: "Volatility 3",
        description: "Memory forensics framework",
        long_description: "Extracts artifacts from RAM dumps. Windows/Linux/macOS.",
        icon: "🧠", category: ToolCategory::Forensics, subcategory: "Memory Forensics",
        command: "volatility3", package: "volatility3",
        tags: &["memory","forensics","ram","malware","windows","linux","rootkit"],
        difficulty: Difficulty::Advanced, color: "#ef4444",
        website: "https://volatilityfoundation.org", is_gui: false,
    },
    Tool {
        name: "binwalk", display_name: "Binwalk",
        description: "Firmware analysis & extraction",
        long_description: "Analyzes, extracts firmware images. Entropy analysis.",
        icon: "🔍", category: ToolCategory::Forensics, subcategory: "Firmware",
        command: "binwalk", package: "binwalk",
        tags: &["firmware","extraction","iot","entropy","signatures"],
        difficulty: Difficulty::Intermediate, color: "#f97316",
        website: "https://github.com/ReFirmLabs/binwalk", is_gui: false,
    },
    // ── POST-EXPLOITATION ──────────────────────────────────────────────────
    Tool {
        name: "bloodhound", display_name: "BloodHound",
        description: "Active Directory attack path visualizer",
        long_description: "Maps AD attack paths via graph theory. Shortest paths to DA.",
        icon: "🐕", category: ToolCategory::PostExploitation, subcategory: "Active Directory",
        command: "bloodhound", package: "bloodhound",
        tags: &["ad","graph","paths","domain-admin","acl","kerberos","neo4j"],
        difficulty: Difficulty::Advanced, color: "#ef4444",
        website: "https://bloodhound.readthedocs.io", is_gui: true,
    },
    Tool {
        name: "chisel", display_name: "Chisel",
        description: "Fast TCP/UDP tunnel over HTTP",
        long_description: "Encrypted TCP/UDP tunnels over HTTP. SOCKS5, reverse tunnels.",
        icon: "🪓", category: ToolCategory::PostExploitation, subcategory: "Pivoting",
        command: "chisel", package: "chisel",
        tags: &["tunnel","pivot","http","socks5","firewall","bypass"],
        difficulty: Difficulty::Intermediate, color: "#f97316",
        website: "https://github.com/jpillora/chisel", is_gui: false,
    },
    Tool {
        name: "ligolo-ng", display_name: "Ligolo-ng",
        description: "Transparent network pivoting via TUN",
        long_description: "Creates virtual TUN interface for transparent pivoting.",
        icon: "🌀", category: ToolCategory::PostExploitation, subcategory: "Pivoting",
        command: "ligolo-ng", package: "ligolo-ng",
        tags: &["tunnel","pivot","tun","routing","transparent","firewall"],
        difficulty: Difficulty::Advanced, color: "#ef4444",
        website: "https://github.com/nicocha30/ligolo-ng", is_gui: false,
    },
    Tool {
        name: "linpeas.sh", display_name: "LinPEAS",
        description: "Linux privilege escalation scanner",
        long_description: "SUID/SGID, sudo misconfigs, cron jobs, capabilities, 250+ checks.",
        icon: "🐧", category: ToolCategory::PostExploitation, subcategory: "Privilege Escalation",
        command: "linpeas.sh", package: "peass-ng",
        tags: &["privesc","linux","suid","sudo","cron","kernel","capabilities"],
        difficulty: Difficulty::Beginner, color: "#ef4444",
        website: "https://github.com/carlospolop/PEASS-ng", is_gui: false,
    },
    Tool {
        name: "msfvenom", display_name: "msfvenom",
        description: "Payload generator & encoder",
        long_description: "Generate payloads in 40+ formats. Encode to evade AV.",
        icon: "💊", category: ToolCategory::Evasion, subcategory: "Payload Generation",
        command: "msfvenom", package: "metasploit",
        tags: &["payload","encode","av-bypass","shellcode","stageless","dropper"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://metasploit.com", is_gui: false,
    },
    // ── SOCIAL ENGINEERING ─────────────────────────────────────────────────
    Tool {
        name: "setoolkit", display_name: "SET",
        description: "Social-Engineer Toolkit",
        long_description: "Phishing, spear-phishing, website cloner, credential harvester.",
        icon: "🎭", category: ToolCategory::SocialEngineering, subcategory: "Phishing",
        command: "setoolkit", package: "set",
        tags: &["phishing","spear-phishing","clone","credentials","payload","se"],
        difficulty: Difficulty::Intermediate, color: "#eab308",
        website: "https://github.com/trustedsec/social-engineer-toolkit", is_gui: false,
    },
    Tool {
        name: "gophish", display_name: "GoPhish",
        description: "Open-source phishing simulation",
        long_description: "Web-based phishing campaign management. Credential tracking.",
        icon: "🎣", category: ToolCategory::SocialEngineering, subcategory: "Phishing",
        command: "gophish", package: "gophish",
        tags: &["phishing","campaigns","tracking","awareness","web","email"],
        difficulty: Difficulty::Intermediate, color: "#ef4444",
        website: "https://getgophish.com", is_gui: true,
    },
    // ── VULNERABILITY ANALYSIS ─────────────────────────────────────────────
    Tool {
        name: "gvm-cli", display_name: "OpenVAS / GVM",
        description: "Enterprise vulnerability scanner — 80k+ tests",
        long_description: "Open Vulnerability Assessment System with 80,000+ NVTs.",
        icon: "🩺", category: ToolCategory::VulnerabilityAnalysis, subcategory: "Network Scanner",
        command: "gvm-cli", package: "gvm",
        tags: &["cve","scanner","enterprise","nvts","network","compliance","nessus"],
        difficulty: Difficulty::Intermediate, color: "#3b82f6",
        website: "https://openvas.org", is_gui: true,
    },
];

pub fn by_category(cat: &ToolCategory) -> Vec<&'static Tool> {
    RED_TEAM_TOOLS.iter()
        .filter(|t| std::mem::discriminant(&t.category) == std::mem::discriminant(cat))
        .collect()
}

pub fn search(query: &str) -> Vec<&'static Tool> {
    let q = query.to_lowercase();
    RED_TEAM_TOOLS.iter().filter(|t| {
        t.name.to_lowercase().contains(&q)
            || t.display_name.to_lowercase().contains(&q)
            || t.description.to_lowercase().contains(&q)
            || t.tags.iter().any(|tag| tag.contains(q.as_str()))
            || t.subcategory.to_lowercase().contains(&q)
    }).collect()
}

pub fn categories() -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    RED_TEAM_TOOLS.iter()
        .filter_map(|t| { let cat = format!("{:?}", t.category); seen.insert(cat.clone()).then_some(cat) })
        .collect()
}

pub fn subcategories() -> Vec<String> {
    let mut seen = std::collections::HashSet::new();
    RED_TEAM_TOOLS.iter()
        .filter_map(|t| seen.insert(t.subcategory).then_some(t.subcategory.to_string()))
        .collect()
}
